### ISSUE TITLE
[5pts](Front/Back)end: Connect Toggling Favorite Foods

### ISSUE THREAD

**Issue by RafaelPiloto10** [Bestagons/quack#119]
**Fill in the blanks**:
As a user, I would like to permanently toggle favorite foods, so that when the app is closed, removed, or deleted I still preserve liked food.

**Describe the solution you'd like:**
- [ ] On food like toggle, make `POST` request to backend to indicate toggle change
- [ ] On food like toggle, backend should listen for said `POST` request and update database accordingly
- [ ] Backend should respond with appropriate status codes or error on failure
- [ ] Frontend should handle any errors by undoing the toggle

**Definition of Done - Check as you go!**
- [ ] Tasks have been implemented
- [ ] Documented
- [ ] Passing Tests for each task
- [ ] Pull Request made
- [ ] Code Reviewed

**Comment by Foxworth22** [comment]
@DDavid233 or @RafaelPiloto10 can either of you provide an update here and tag me?

**Comment by Foxworth22** [comment]
Backend done. Frontend in progress.
