### ISSUE TITLE
[6pts] Sprint 10: Get App on Each of Our Phones

### ISSUE THREAD

**Issue by Foxworth22** [Bestagons/quack#136]
**Fill in the blanks**:
This task will be complete when each scrum team member can run and login to the app on their phone.

**How frequent is this task?**:
- ( ) Weekly
- (X) Once

**Comment by Foxworth22** [comment]
@RafaelPiloto10 By chance, is our app downloadable yet?

**Comment by RafaelPiloto10** [comment]
@Foxworth22 not yet -- we need to merge all final branches and update URLs to use production backends.

**Comment by Foxworth22** [comment]
@RafaelPiloto10 Okay, once we're ready I recommend something like this: https://docs.flutter.dev/deployment/ios#release-your-app-on-testflight
