### ISSUE TITLE
[21pts] Webscraping of Bon Appetit

### ISSUE THREAD

**Issue by Foxworth22** [Bestagons/quack#17]
**Fill in the blanks**:
As a developer, I would like to Webscrape Bon Appetit, so that We have a data structure that contains the DCT menus.

**Definition of Done - Check as you go!**
- [x] Tasks have been implemented
- [x] Documented
- [ ] Passing Tests for each task
- [x] Pull Request made
- [ ] Code Reviewed

**Comment by Foxworth22** [comment]
Work closely with DCT Backend person

**Comment by Foxworth22** [comment]
Tutorial: https://realpython.com/beautiful-soup-web-scraper-python/#challenges-of-web-scraping

**Comment by Foxworth22** [comment]
Base URL: https://emoryatlanta.cafebonappetit.com/cafe/dobbs-common-table/

**Comment by Foxworth22** [comment]
Get up & running quick: https://youtu.be/O6nnVHPjcJU

**Comment by Foxworth22** [comment]
git status //all files modified
git add .
git commit -m 'message'
git push origin branchName //adds changes to GitHub

git checkout branchName //cd to different branch

git pull origin branchName //sync

git checkout -b branchName //create new branch

**Comment by Foxworth22** [comment]
Ubuntu

code .

**Comment by RafaelPiloto10** [comment]
Bugs to consider and be aware of: During the day, the column for the eating time that is currently being served is automatically opened (aka Active) so the class elements may look different.

Ex:
You find elements by a class X. It is currently Lunch time, Bon Appetite automatically shows Lunch. Therefore Lunch has class Y but all other rows have class X because they are not opened/active.

**Comment by Foxworth22** [comment]
> Bugs to consider and be aware of: During the day, the column for the eating time that is currently being served is automatically opened (aka Active) so the class elements may look different.
> 
> Ex: You find elements by a class X. It is currently Lunch time, Bon Appetite automatically shows Lunch. Therefore Lunch has class Y but all other rows have class X because they are not opened/active.

Fortunately, only the spacing changes, therefore this has not been an issue thus far.

**Comment by Foxworth22** [comment]
Added scraping of meal times, food items, and meal stations names

Next:
- [ ] Work on backend data structures to associate different scrapes
- [ ] Scrape more things!

**Comment by RafaelPiloto10** [comment]
It should be closed when the branch is merged

**Comment by RafaelPiloto10** [comment]
@Foxworth22 please close this when your pull request has been merged. Closing it implies the job is done and can get lost in our stack of tickets.

**Comment by Foxworth22** [comment]
But it's ready to be demoed, also, the scraper pull request is still marking its progress...

**Comment by RafaelPiloto10** [comment]
@Foxworth22, #138 and #135 are not merged therefore my issue is not closed. In addition, you have not written unit tests for the scraper. Let's remain consistent with how everyone else has done it. In addition, when you mark this issue as closed, you state that you have met the definition of done. Your PR has not been merged and you do not have tests yet. It skews our velocity and creates a false sense of completion

**Comment by Foxworth22** [comment]
The last sentence was unnecessary.

**Comment by Foxworth22** [comment]
@RafaelPiloto10 The last sentence was unnecessary. 😠

**Comment by RafaelPiloto10** [comment]
@Foxworth22 I am not sure what you are referring to? I think you are reading too much into it. I am simply stating that closing this issue creates a false sense of completion that the job is done and skews our velocity. If you would like, I am happy to resolve this privately
