### ISSUE TITLE
[3pts] Draw Maps of Directions to each food station

### ISSUE THREAD

**Issue by Foxworth22** [Bestagons/quack#18]
**Fill in the blanks**:
As a student, I would like to be able to visualize how to get to the the food I want to eat, so that I can be most efficient when I get to the DCT.

**Definition of Done - Check as you go!**
- [x] Tasks have been implemented
- [x] Documented
- [ ] Passing Tests for each task
- [ ] Pull Request made
- [ ] Code Reviewed

**Comment by brendacano** [comment]
Can I get some feedback?
![dctmapbare_v1](https://user-images.githubusercontent.com/69967655/135701801-781396cd-3b17-4384-9042-b4611228a1a1.png)
![dctmapsections_v1](https://user-images.githubusercontent.com/69967655/135701804-b5506565-0980-477e-b2cf-f86e191b719e.png)

**Comment by RafaelPiloto10** [comment]
@brendacano, I like the station coloring! It was hard for me to figure out what station was where. Can you label major points like stations, entrance, bathroom, exit

**Comment by brendacano** [comment]
Updated maps:

1. dct map with everything
![dctmapall_v2](https://user-images.githubusercontent.com/69967655/135732352-a6c3983b-6bff-4abc-af47-fca1d7516467.png)

2. dct map with only the stations
![dctmapstations_v2](https://user-images.githubusercontent.com/69967655/135732364-e7d80d86-6feb-47d8-9d11-c908fdc16a47.png)

3. dct map with only the sections
![dctmapsections_v2](https://user-images.githubusercontent.com/69967655/135732374-248f7e36-dae2-4a15-926e-51587a1c1ed7.png)

4. dct map no labels
![dctmapbare_v2](https://user-images.githubusercontent.com/69967655/135732381-97989df3-3248-49e2-84a8-e1c44799dced.png)

5. dct map with only section 1 (I can isolate each section or anything we need)
![dctmapsection1_v2](https://user-images.githubusercontent.com/69967655/135732413-5c4c58f4-ffad-4959-bb27-3c4c74c7effd.png)


@Foxworth22 Please let me know what you think and if this fits with our product and with anything else you wanted to add to the maps

**Comment by RafaelPiloto10** [comment]
@brendacano nice work on this! They will be helpful for each scenario

**Comment by brendacano** [comment]
> @brendacano nice work on this! They will be helpful for each scenario

I appreciate your feedback. I am slightly worried about how it will look in the app and if it will be user-friendly or not.

**Comment by MimiOlayeye** [comment]
@brendacano this looks great! I love the simplicity,  it makes it really easy to understand! 

Since the map is color-coded instead of overlapping the text over the station, maybe you could do a key instead.

**Comment by Foxworth22** [comment]
Wow! I never realized how complex DCT was until I looked at this map. Nice job so far!

**Comment by Foxworth22** [comment]
The dessert section seems a little small to me...

**Comment by Foxworth22** [comment]
Also I think there's a divider somewhere between sections 3 & 5.

**Comment by brendacano** [comment]
> Also I think there's a divider somewhere between sections 3 & 5. 

Thanks for your feedback Miles, especially since you go to the DCT more often. I will work on making any changes today.

**Comment by brendacano** [comment]
So I addressed the comments you all left.

> @brendacano this looks great! I love the simplicity, it makes it really easy to understand!
> Since the map is color-coded instead of overlapping the text over the station, maybe you could do a key instead.

^ For @MimiOlayeye I like the idea of a key however I do think we should keep the name of the section on the color. I know it looks a bit busy but I think keeping the name on the color would make it more inclusive for people who are color blind. 

> The dessert section seems a little small to me...

^ For @Foxworth22 I talked with other people who go to the DCT and they agreed it was small so I enlarged it

> Also I think there's a divider somewhere between sections 3 & 5.

^ There isn't a divider there.

________________________________________________________________________________________


Here are some of the updated graphs. I can isolate anything we need. I can also upload them to our google drive.



![dctmapall_v3](https://user-images.githubusercontent.com/69967655/135784594-c52bd9f6-7613-4448-bfcf-2c17a2e29e3c.png)



![dctmapallwithkey_v3](https://user-images.githubusercontent.com/69967655/135784607-9f127fea-ecc8-48a6-9e8b-d0c262f0c7de.png)



![dctmapstations_v3](https://user-images.githubusercontent.com/69967655/135784621-91eb09f0-38df-49a6-a8f9-e636adc845a2.png)



![dctmapbare_v3](https://user-images.githubusercontent.com/69967655/135784655-0fa5fe80-7e5f-45a2-ad09-8a3d0367f840.png)



![dctmapsection1_v3](https://user-images.githubusercontent.com/69967655/135784674-ed97e0ea-a445-4db1-b12e-075c1d94daba.png)



![dctmapsectionhearthandstone_v3](https://user-images.githubusercontent.com/69967655/135784683-5fdea21f-1f66-45a1-afc8-de6c46c16f25.png)

**Comment by RafaelPiloto10** [comment]
@brendacano LGTM (Looks good to me)

**Comment by brendacano** [comment]
All the images are uploaded to our Google Drive in a folder called DCT Maps
