### ISSUE TITLE
[2pts] Design Logo

### ISSUE THREAD

**Issue by Foxworth22** [Bestagons/quack#2]
Once we have a logo for our project we can create Zoom backgrounds to increase our professionalism at Demo. 
- [x] Update Slack Logo
- [x] Create Zoom Backgrounds
- [x] Update GitHub Logo

**Comment by RafaelPiloto10** [comment]
Logo can also be used for GitHub organization, Repository, and App

**Comment by brendacano** [comment]
> Logo can also be used for GitHub organization, Repository, and App

So would yall both agree that this logo be the same for everything?

**Comment by brendacano** [comment]
Placing this here to get some feedback. If it gets approved I can send the files in the slack channel
![BestagonsLogo](https://user-images.githubusercontent.com/69967655/134436843-adae8b87-4ef1-4512-8378-583842abdf4d.png)
![bestagonszoomtest (1)](https://user-images.githubusercontent.com/69967655/134436856-3bf0106b-e64c-42fb-8d72-2a7f8baa52e8.png)

**Comment by RafaelPiloto10** [comment]
That's so amazing! Love it!
