### ISSUE TITLE
[5pts] DCT Backend: Reviews of Food

### ISSUE THREAD

**Issue by Foxworth22** [Bestagons/quack#22]
**Fill in the blanks**:
As a student, I would like to rate the food I ate, so that feedback can be given to Emory Dining for what food should(n't) be served.

**Definition of Done - Check as you go!**
- [x] Tasks have been implemented
- [x] Documented
- [x] Passing Tests for each task
- [x] Pull Request made
- [ ] Code Reviewed

**Comment by Foxworth22** [comment]
BACKEND

**Comment by Foxworth22** [comment]
Front end will be +2 points

**Comment by MimiOlayeye** [comment]
putting this in DCT backend, because I need access to the FoodItem() object
