### ISSUE TITLE
[2pts] App Backend "Hello World"

### ISSUE THREAD

**Issue by Foxworth22** [Bestagons/quack#32]
**Fill in the blanks**:
As a developer, I would like to make GET/POST requests, so that data is communicated from the frontend and backend.

**Definition of Done - Check as you go!**
- [ ] Tasks have been implemented
- [ ] Documented
- [ ] Passing Tests for each task
- [ ] Pull Request made
- [ ] Code Reviewed

**Comment by RafaelPiloto10** [comment]
@Foxworth22, this is assigned for Sprint 2. There is also another issue assigned to Spring 2 -- just wanted to make sure that was intentional and not an accident

**Comment by Foxworth22** [comment]
> wanted to make sure that was intentional and not an accident

This was intentional. They are intended to be started on during Sprint 1, but not needed to be finished until Sprint 2.
