### ISSUE TITLE
[5pts] <3 Screen

### ISSUE THREAD

**Issue by Foxworth22** [Bestagons/quack#51]
**Fill in the blanks**:
As a student, I would like to see a list of my starred foods, so that I can unstar any foods that I no longer want starred in a bulk format.

**Describe the solution you'd like:**
- [x] Add a title to identify the page
- [x] Create a visual that connects to a DCT backend queue/dictionary
- [x] Create a visual blueprint for each item in the queue/dictionary
- [ ] Have a 'filters' button to add functionality to later
- [x] Have a 'back' button to add functionality to later
- [x] Contains Nav Bar to add functionality to later

**Definition of Done - Check as you go!**
- [x] Tasks have been implemented
- [x] Documented
- [x] Passing Tests for each task
- [x] Pull Request made
- [x] Code Reviewed

**Comment by DDVD233** [comment]
Sprint 3
- Created a reusable class representing food cell in a table
- Clean up old code to make it look better suited for future use
