### ISSUE TITLE
[2pts] App Backend: Save New <3

### ISSUE THREAD

**Issue by Foxworth22** [Bestagons/quack#73]
**Fill in the blanks**:
As a developer, I would like to have a helper method that saves new hearted items, so that the method can be reused.

**Describe the solution you'd like:**
- [ ] Parameter(s): food item object
- [ ] Return: heart already exists boolean

**Definition of Done - Check as you go!**
- [ ] Tasks have been implemented
- [ ] Documented
- [ ] Passing Tests for each task
- [ ] Pull Request made
- [ ] Code Reviewed

**Comment by Foxworth22** [comment]
How soon will this be done?

**Comment by DDVD233** [comment]
This is finished. I am waiting for the login logic to be done so that I can connect the actual data.
