### ISSUE TITLE
[2pts] DCT Backend: Save Food Station

### ISSUE THREAD

**Issue by Foxworth22** [Bestagons/quack#90]
**Fill in the blanks**:
As a developer, I would like to have a helper method that saves food stations from the BonAppetit website, so that the method can be reused.

**Describe the solution you'd like:**
- [ ] Parameter(s): string fooditem, string foodStation
- [ ] Return: updated food object/row in database

**Definition of Done - Check as you go!**
- [ ] Tasks have been implemented
- [ ] Documented
- [ ] Passing Tests for each task
- [ ] Pull Request made
- [ ] Code Reviewed

**Comment by RafaelPiloto10** [comment]
@brendacano, please see the linked pull request and branch off to make any modifications you may desire. I think this was as simple as adding it to a constructor I didn't realize there were separate cards.

**Comment by brendacano** [comment]
> @brendacano, please see the linked pull request and branch off to make any modifications you may desire. I think this was as simple as adding it to a constructor I didn't realize there were separate cards.

Omg I was wondering how to have it in separate files. I don't know why I was having trouble with that before. Also what did you do to know how to do your ticket stuff  (unless you already knew?)?

**Comment by RafaelPiloto10** [comment]
> > @brendacano, please see the linked pull request and branch off to make any modifications you may desire. I think this was as simple as adding it to a constructor I didn't realize there were separate cards.
> 
> Omg I was wondering how to have it in separate files. I don't know why I was having trouble with that before. Also what did you do to know how to do your ticket stuff (unless you already knew?)?

I think the description to these tickets were a little confusing. In a way, splitting them into individual tickets overcomplicates the functionality.

We don't ever need to set a station name for a food item - when we web-scrape we will have all that information at once so we can just store that food item with the parsed information. That'll heavily improve run time performance.

So really, its just a matter of creating an object that can keep track of that information, hence the `FoodItem`. Having an understanding of how we are going to process the webscrapped data really helped me make that decision.

Does that help? As per your ticket, I am not sure we really need to do any additional stuff at this time - We'll have a better idea about how this all interacts once we have the webscrapping functionality implemented.

**Comment by brendacano** [comment]
> > > @brendacano, please see the linked pull request and branch off to make any modifications you may desire. I think this was as simple as adding it to a constructor I didn't realize there were separate cards.
> > 
> > 
> > Omg I was wondering how to have it in separate files. I don't know why I was having trouble with that before. Also what did you do to know how to do your ticket stuff (unless you already knew?)?
> 
> I think the description to these tickets were a little confusing. In a way, splitting them into individual tickets overcomplicates the functionality.
> 
> We don't ever need to set a station name for a food item - when we web-scrape we will have all that information at once so we can just store that food item with the parsed information. That'll heavily improve run time performance.
> 
> So really, its just a matter of creating an object that can keep track of that information, hence the `FoodItem`. Having an understanding of how we are going to process the webscrapped data really helped me make that decision.
> 
> Does that help? As per your ticket, I am not sure we really need to do any additional stuff at this time - We'll have a better idea about how this all interacts once we have the webscrapping functionality implemented.

Yeah this helps. I was wondering more on how the frontend would interact since the front end needs the stuff like the food stations and so there would be a get request to get the food stations from the database (which the database stored from the web scraping) if you know what I'm saying? That way the front end calls this get request. Or is this out of the scope of the ticket or does it not make sense
