### ISSUE TITLE
[2pts] DCT Backend: Save Food Meal Time

### ISSUE THREAD

**Issue by Foxworth22** [Bestagons/quack#91]
**Fill in the blanks**:
As a developer, I would like to have a helper method that saves a meal time with its associated food item from the BonAppetit website, so that the method can be reused.

**Describe the solution you'd like:**
- [ ] Parameter(s): string fooditem, string mealTime
- [ ] Return: updated food object/row in database

**Definition of Done - Check as you go!**
- [ ] Tasks have been implemented
- [ ] Documented
- [ ] Passing Tests for each task
- [ ] Pull Request made
- [ ] Code Reviewed

**Comment by RafaelPiloto10** [comment]
@oreorz, please see the linked pull request and branch off to make any modifications you may desire. I think this was as simple as adding it to a constructor I didn't realize there were separate cards.

**Comment by oreorz** [comment]
> @oreorz, please see the linked pull request and branch off to make any modifications you may desire. I think this was as simple as adding it to a constructor I didn't realize there were separate cards.

Looks like you already did this, I'm just gonna close this ticket then. I think just adding it to the constructor rather than a whole method (as described in the task) is sufficient for what we need
