### ISSUE TITLE
[2pts] DCT Backend: Save Capacity (Seated + Takeout)

### ISSUE THREAD

**Issue by Foxworth22** [Bestagons/quack#93]
**Fill in the blanks**:
As a developer, I would like to have a helper method that saves and updates current DCT capacity so that the method can be reused.

**Describe the solution you'd like:**
- [ ] Parameter(s): int capacity
- [ ] Return: updated capacity value

**Definition of Done - Check as you go!**
- [ ] Tasks have been implemented
- [ ] Documented
- [ ] Passing Tests for each task
- [ ] Pull Request made
- [ ] Code Reviewed

**Comment by Foxworth22** [comment]
How soon will this be done?

**Comment by brendacano** [comment]
> How soon will this be done?

I am waiting on another approval for the PR opened for this https://github.com/Bestagons/quack/pull/113
